version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    groups:
      pip-non-major:
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
    target-branch: main
    groups:
      docker-non-major:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    groups:
      actions-non-major:
        update-types:
          - minor
          - patch
