name: Publish Docker Image

on:
  workflow_call:

jobs:
  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate tag format
        run: |
          if [[ ! $GITHUB_REF =~ ^refs/tags/release/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid tag format. Expected 'release/major.minor.patch'."
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/release/}" >> $GITHUB_ENV

      - name: Write VERSION file
        run: echo ${{ env.VERSION }} > VERSION

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: false
          tags: |
            drache42/wakeonlanservice:${{ env.VERSION }}
            drache42/wakeonlanservice:latest

      - name: Verify Docker image
        run: docker run --rm drache42/wakeonlanservice:${{ env.VERSION }} --version