name: Integration tests

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  test:
    name: Integration tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Create test results directory
        run: mkdir -p test-results

      - name: Run integration tests
        run: poetry run pytest tests/integration -v --log-cli-level=INFO --junitxml=test-results/integration.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-results-integration
          path: test-results/
          if-no-files-found: warn