name: Lint

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  lint:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: "poetry"

      - name: Install poetry
        run: pipx install poetry
        
      - name: Install dependencies
        run: |
          poetry install

      - name: Run Ruff
        run: |
          poetry run ruff check .