name: Lint

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  lint:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Common setup
        uses: ./.github/workflows/common-setup.yml@main
        with:
          python-version: ${{ inputs.python-version }}

      - name: Run Ruff
        run: |
          poetry run ruff check .