name: Main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'refs/tags/release/**'
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/linter.yml
    with:
      python-version: "3.13"

  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    with:
      matrix: |
        ["3.9", "3.10", "3.11", "3.12", "3.13"]

  integration-tests:
    uses: ./.github/workflows/integration-tests.yml
    with:
      python-version: "3.13"

  docker-publish:
    needs: [lint, unit-tests, integration-tests]
    if: startsWith(github.ref, 'refs/tags/release/')
    uses: ./.github/workflows/docker-publish.yml