name: Unit tests

on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string

jobs:
  test:
    name: Pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJson(inputs.matrix) }}
    steps:
      - name: Common setup
        uses: ./.github/workflows/common-setup.yml@main
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: |
          poetry run pytest