name: CI Pipeline

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
        
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Run tests
      run: |
        poetry run pytest